
__desc__ = __doc__

css_file = """
body {
font-family: "lucida grande", "sans serif";
color: #333;
width: 60em;
margin: auto;
}


div.main {
padding: 20px;
margin: auto;
padding-top: 0;
margin-top: 1em;
background-color: #fcfcfc;
}

.even-row {
background-color: #e9e9e2;
width: 5%;
}

.odd-row {

background-color: #f9f9f9;
width: 5%;
}

.person {
font-family: courier;
}

a, a:visited {
background: inherit;
text-decoration: none;
}

a {
color: #003d41;
}

a:visited {
color: #553d41;
}

ul {
list-style-type: none;
padding: 0;
}

p {
width: 40em;
}

.inline-status-image {
position: relative;
top: 0.2em;
}

.dimmed {
color: #bbb;
}

table {
border-style: none;
border-spacing: 0;
}

table.log {
}


td {
border-width: 0;
border-style: none;
padding-right: 0.5em;
padding-left: 0.5em;
}

tr {
vertical-align: top;
}

h1 {
padding: 0.5em;
background-color: #305275;
margin-top: 0;
margin-bottom: 0;
color: #fff;
margin-left: -20px;
margin-right: -20px;  
}

h2 {
text-transform: uppercase;
font-size: smaller;
margin-top: 1em;
margin-left: -0.5em;  
/*background: #fffbce;*/
/*background: #628a0d;*/
padding: 5px;
color: #305275;
}



.attrname {
text-align: right;
font-size: smaller;
}

.attrval {
color: #222;
}

.issue-closed-fixed {
background-image: "green-check.png";
}

.issue-closed-wontfix {
background-image: "red-check.png";
}

.issue-closed-reorg {
background-image: "blue-check.png";
}

.inline-issue-link {
text-decoration: underline;
}

img {
border: 0;
}


div.footer {
font-size: small;
padding-left: 20px;
padding-right: 20px;
padding-top: 5px;
padding-bottom: 5px;
margin: auto;
background: #305275;
color: #fffee7;
}

.footer a {
color: #508d91;
}


.header {
font-family: "lucida grande", "sans serif";
font-size: smaller;
background-color: #a9a9a9;
text-align: left;

padding-right: 0.5em;
padding-left: 0.5em;

}


.selected-cell {
background-color: #e9e9e2;
}

.plain-cell {
background-color: #f9f9f9;
}

.backptr {
font-size: smaller;
width: 100%;
text-align: left;
padding-bottom: 1em;
margin-top: 0;
}

.logcomment {
padding-left: 4em;
font-size: smaller;
}

.id {
font-family: courier;
}

.description {
background: #f2f2f2;
padding-left: 1em;
padding-right: 1em;
padding-top: 0.5em;
padding-bottom: 0.5em;
}

.message {
}

.littledate {
font-size: smaller;
}

.progress-meter-done {
background-color: #03af00;
}

.progress-meter-undone {
background-color: #ddd;
}

.progress-meter {
}
"""

index_first = """
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>BugsEverywhere Issue Tracker</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="style.css" type="text/css" />
</head>
<body>


<div class="main">
<h1>BugsEverywhere Bug List</h1>
<h2>Open Bugs</h2>
<table width=100%>
<tbody>
"""    

bug_line ="""
<tr class=_ROW_>
    <td><a href="bugs/_bug_id_link_.html">_bug_id_</a></td>
    <td><a href="bugs/_bug_id_link_.html">_status_</a></td>
    <td><a href="bugs/_bug_id_link_.html">_sev_</a></td>
    <td><a href="bugs/_bug_id_link_.html">_descr_</a></td>
    <td><a href="bugs/_bug_id_link_.html">_time_</a></td>
</tr>
"""
        
index_last = """
</tbody>
</table>

</div>

<h2>Show all bugs</h2>

<div class="footer">Generated by <a href="http://www.bugseverywhere.org/">BugsEverywhere</a>.</div>

</body>
</html>
"""

